import modules

In [142]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split


load insurance data

In [143]:
df = pd.read_csv("C:\\Users\\a\\Desktop\\Machine Learning Projects\\insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

scaling age field

In [144]:
df['age'] = df['age']/100
df

age  bought_insurance
0   0.22                 0
1   0.25                 0
2   0.47                 1
3   0.52                 0
4   0.46                 1
5   0.56                 1
6   0.55                 0
7   0.60                 1
8   0.62                 1
9   0.61                 1
10  0.18                 0
11  0.28                 0
12  0.27                 0
13  0.29                 0
14  0.49                 1
15  0.55                 1
16  0.25                 1
17  0.58                 1
18  0.19                 0
19  0.18                 0
20  0.21                 0
21  0.26                 0
22  0.40                 1
23  0.45                 1
24  0.50                 1
25  0.54                 1
26  0.23                 0

train test split

In [145]:
x_train,x_test,y_train,y_test = train_test_split(df['age'],df['bought_insurance'],random_state=3,test_size=0.2)
x_train.shape

(21,)

now make model

In [146]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (1,),activation='sigmoid',bias_initializer='zeros',kernel_initializer='ones')
])

now compile the model

In [147]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=['accuracy']
)

model.fit(x_train,y_train,epochs=5000)

Epoch 1/5000


1/1 [==============================] - 1s 839ms/step - loss: 0.6681 - accuracy: 0.4762
Epoch 2/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.6680 - accuracy: 0.4762
Epoch 3/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.6678 - accuracy: 0.4762
Epoch 4/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.6677 - accuracy: 0.4762
Epoch 5/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6676 - accuracy: 0.4762
Epoch 6/5000
1/1 [==============================] - 0s 8ms/step - loss: 0.6675 - accuracy: 0.4762
Epoch 7/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6673 - accuracy: 0.4762
Epoch 8/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.6672 - accuracy: 0.4762
Epoch 9/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.6671 - accuracy: 0.4762
Epoch 10/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.6670 - accuracy: 0.4762
Epoch 11/5000
1/1 [===========

now predict 

In [148]:
x_train

13    0.29
2     0.47
1     0.25
23    0.45
14    0.49
4     0.46
22    0.40
6     0.55
7     0.60
5     0.56
20    0.21
9     0.61
11    0.28
26    0.23
19    0.18
21    0.26
0     0.22
8     0.62
3     0.52
24    0.50
10    0.18
Name: age, dtype: float64

In [149]:
y_train

13    0
2     1
1     0
23    1
14    1
4     1
22    1
6     0
7     1
5     1
20    0
9     1
11    0
26    0
19    0
21    0
0     0
8     1
3     0
24    1
10    0
Name: bought_insurance, dtype: int64

In [150]:
model.predict(x_train)

1/1 [==============================] - 0s 104ms/step


array([[0.3130566 ],
       [0.59262794],
       [0.2604169 ],
       [0.5611603 ],
       [0.6233537 ],
       [0.57697225],
       [0.48087275],
       [0.7090367 ],
       [0.7708521 ],
       [0.7221585 ],
       [0.21387264],
       [0.78204316],
       [0.29935908],
       [0.23635456],
       [0.18314412],
       [0.27302688],
       [0.22491428],
       [0.79283446],
       [0.6675797 ],
       [0.6383688 ],
       [0.18314411]], dtype=float32)

In [151]:
coef,intercepts = model.get_weights()
coef,intercepts

(array([[6.4483767]], dtype=float32), array([-2.6558971], dtype=float32))

Now the most interesting thing iam going to build my my own model but first of all i need to clear concept in activation function.So first of all iam learning here about activation 

Sigmoid Function Implementation it returns [0,1]

In [152]:
import math
def sigmoidFunction(x):
    val = 1/(1+math.exp(-x))
    return val
sigmoidFunction(300)

1.0

tanh function function returns [-1,1]


In [153]:
def tanh(x):
    val = (math.exp(x) - math.exp(-x))/(math.exp(x)+math.exp(-x))
    return val

tanh(-100)

-1.0

relu function implementation it returns max(0,x)

In [154]:
def relu(x):
    return max(0,x)

relu(-1)

0

Implementation of LRelu it returns max(0.1x,x)

In [155]:
def leakyRelu(x):
    return max(0.1*x,x)

leakyRelu(-100)

-10.0

Now we need to know about cost function

Implementatiin of Mean Absolute Error  that is      sum (abs(ytrue - ypred))   /  n
Mean Squared Error = sum(abs(ytrue-ypred)*abs(ytrue-ypred))/n

log loss or binary_crossentropy = -sum(ytrue log(ypred)+(1-ytrue) .log(1-ypred)) /n

In [156]:
ypred = np.array([1,0.75,0,1,0.8])
ytrue = np.array([1,0.5,0.5,0.5,1])

mean absolute error

In [157]:
def mae(ytrue,ypred):
    return np.mean(np.abs(ytrue - ypred))

mae(ytrue,ypred)

0.29

mean squared error  home work 

log loss or binary_crossentropy

In [158]:
epsilon = 1e-15
ypredNew = [max(i,epsilon)for i in ypred]

ypredNew
    

[1.0, 0.75, 1e-15, 1.0, 0.8]

In [159]:
ypredNew = np.array([min(i,1-epsilon)for i in ypredNew])
ypredNew

array([1.0e+00, 7.5e-01, 1.0e-15, 1.0e+00, 8.0e-01])

In [160]:
-np.mean(ytrue*np.log(ypredNew)+(1-ytrue)*(np.log(1-ypredNew)))

7.119861592345165

Gradient Descent


In [161]:
coef[0]

array([6.4483767], dtype=float32)

my custom prediction sum

In [162]:
def prediction_function(age):
    weightedSum = coef[0]*age + intercepts
    return sigmoidFunction(weightedSum)
prediction_function(0.58)

0.7472806591922565

check with modules

In [163]:
x_test

18    0.19
17    0.58
12    0.27
25    0.54
15    0.55
16    0.25
Name: age, dtype: float64

In [164]:
model.predict(x_test)

1/1 [==============================] - 0s 40ms/step


array([[0.19298877],
       [0.74728066],
       [0.2860114 ],
       [0.69555646],
       [0.7090367 ],
       [0.2604169 ]], dtype=float32)

custom gradient descent function

In [165]:
def sigmoidNumpyFunction(x):
    val = 1/(1+np.exp(-x))
    return val


In [166]:
def logLossFunction(ytrue, ypredNew):
    epsilon = 1e-15
    ypredNew = np.maximum(ypredNew, epsilon)
    ypredNew = np.minimum(ypredNew, 1 - epsilon)
    loss = -np.mean(ytrue * np.log(ypredNew) + (1 - ytrue) * np.log(1 - ypredNew))
    return loss


In [167]:
def gradient_descent(age,y_train,epochs):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range(epochs):
        weighted_sum = w1*age + bias
        y_predicted = sigmoidNumpyFunction(weighted_sum)
        loss = logLossFunction(y_train,y_predicted)
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted - y_train))
        bias_d = np.mean(y_predicted-y_train)
        w1 = w1 - rate*w1d
        bias = bias - rate*bias_d
        print(f'epoch:{i},w1:{w1},bias:{bias},loss:{loss}')
        
    return w1,bias
        
    

In [168]:
gradient_descent(x_train,y_train,5000)

epoch:0,w1:1.00160237344272,bias:-0.06057833519547148,loss:0.6680903759944049
epoch:1,w1:1.0060300109714218,bias:-0.11394765027608844,loss:0.6611771886310611
epoch:2,w1:1.0129085352030167,bias:-0.16105123156364995,loss:0.6557645452312695
epoch:3,w1:1.021902887857833,bias:-0.2027308028186713,loss:0.6514731390194821
epoch:4,w1:1.0327168032175962,bias:-0.2397288481139358,loss:0.6480156129178406
epoch:5,w1:1.0450906204009844,bias:-0.2726948361830502,loss:0.6451762724970967
epoch:6,w1:1.0587982276474934,bias:-0.30219340887790275,loss:0.6427943116858488
epoch:7,w1:1.073643659142017,bias:-0.3287132784593063,loss:0.6407504409998319
epoch:8,w1:1.0894576662859923,bias:-0.3526760689950849,loss:0.6389564897754304
epoch:9,w1:1.106094449142189,bias:-0.37444466976595825,loss:0.6373474596384264
epoch:10,w1:1.1234286446735744,bias:-0.39433088388901844,loss:0.6358755251159643
epoch:11,w1:1.1413526124642286,bias:-0.41260228891597556,loss:0.6345055435876498
epoch:12,w1:1.1597740250132864,bias:-0.429488305

(15.12607246710615, -6.298945723549974)

In [169]:
class CM:
    def __init__(self):
        self.w1 = 1
        self.bias = 0
    def fit(self,x_train,y_train,epochs,loss_thresold):
        self.w1,self.bias = self.gradient_descent(x_train,y_train,epochs,loss_thresold)
    def gradient_descent(self,age,y_train,epochs,loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        
        for i in range(epochs):
            weighted_sum = w1*age + bias
            y_predicted = sigmoidNumpyFunction(weighted_sum)
            loss = logLossFunction(y_train,y_predicted)
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted - y_train))
            bias_d = np.mean(y_predicted-y_train)
            w1 = w1 - rate*w1d
            bias = bias - rate*bias_d
            print(f'epoch:{i},w1:{w1},bias:{bias},loss:{loss}')
            # if loss<loss_thresold:
            #     break
            
        return w1,bias
            

In [170]:
customModel = CM()
customModel.fit(x_train,y_train,epochs=5000,loss_thresold=0.46)

epoch:0,w1:1.00160237344272,bias:-0.06057833519547148,loss:0.6680903759944049
epoch:1,w1:1.0060300109714218,bias:-0.11394765027608844,loss:0.6611771886310611
epoch:2,w1:1.0129085352030167,bias:-0.16105123156364995,loss:0.6557645452312695
epoch:3,w1:1.021902887857833,bias:-0.2027308028186713,loss:0.6514731390194821
epoch:4,w1:1.0327168032175962,bias:-0.2397288481139358,loss:0.6480156129178406
epoch:5,w1:1.0450906204009844,bias:-0.2726948361830502,loss:0.6451762724970967
epoch:6,w1:1.0587982276474934,bias:-0.30219340887790275,loss:0.6427943116858488
epoch:7,w1:1.073643659142017,bias:-0.3287132784593063,loss:0.6407504409998319
epoch:8,w1:1.0894576662859923,bias:-0.3526760689950849,loss:0.6389564897754304
epoch:9,w1:1.106094449142189,bias:-0.37444466976595825,loss:0.6373474596384264
epoch:10,w1:1.1234286446735744,bias:-0.39433088388901844,loss:0.6358755251159643
epoch:11,w1:1.1413526124642286,bias:-0.41260228891597556,loss:0.6345055435876498
epoch:12,w1:1.1597740250132864,bias:-0.429488305

In [171]:
coef,intercepts = model.get_weights()
coef,intercepts

(array([[6.4483767]], dtype=float32), array([-2.6558971], dtype=float32))